steps:
  - uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      registry-url: https://registry.npmjs.org/

  - run: npm ci
  - run: npm run build-npm

  - name: Publish
    run: cd tmp/test-package && npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
